// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-business-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_business_info_default = defineTool({
  name: "get_business_info",
  title: "Get business info",
  description: "Return contact info, service area, and core details for Highlander Roofing & Construction.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Highlander Roofing & Construction, Inc.",
      phone: "(828) 524-7773",
      website: "https://western-wnc-dominate.lovable.app",
      city: "Franklin",
      region: "North Carolina",
      country: "US",
      service_area: "Western North Carolina \u2014 Macon, Jackson, Swain, Haywood, Transylvania, Henderson, Buncombe, Cherokee, and Clay counties.",
      divisions: ["Roofing", "Construction"],
      credentials: [
        "CertainTeed ShingleMaster Credentialed Contractor",
        "Licensed General Contractor (NC)"
      ],
      positioning: "Premium local roofing and construction team serving Western NC mountain homes since founding. Team-led, mountain-specialized crews."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var services = [
  { slug: "roof-replacement", title: "Roof Replacement", division: "roofing", url: "https://highlandernc.com/roofing/roof-replacement" },
  { slug: "roof-repair", title: "Roof Repair", division: "roofing", url: "https://highlandernc.com/roofing/roof-repair" },
  { slug: "residential", title: "Residential Roofing", division: "roofing", url: "https://highlandernc.com/roofing/residential" },
  { slug: "metal", title: "Metal Roofing", division: "roofing", url: "https://highlandernc.com/roofing/metal" },
  { slug: "brava-synthetic", title: "Brava Synthetic Roofing", division: "roofing", url: "https://highlandernc.com/roofing/brava-synthetic" },
  { slug: "storm-damage", title: "Storm Damage Roofing", division: "roofing", url: "https://highlandernc.com/roofing/storm-damage" },
  { slug: "commercial", title: "Commercial Roofing", division: "roofing", url: "https://highlandernc.com/roofing/commercial" },
  { slug: "specialty", title: "Specialty Roofing", division: "roofing", url: "https://highlandernc.com/roofing/specialty" },
  { slug: "skylights", title: "Skylights", division: "roofing", url: "https://highlandernc.com/roofing/skylights" },
  { slug: "gutters", title: "Gutters", division: "roofing", url: "https://highlandernc.com/roofing/gutters" },
  { slug: "additions", title: "Home Additions", division: "construction", url: "https://highlandernc.com/construction/additions" },
  { slug: "renovations", title: "Renovations", division: "construction", url: "https://highlandernc.com/construction/renovations" },
  { slug: "exterior", title: "Exterior Improvements", division: "construction", url: "https://highlandernc.com/construction/exterior" },
  { slug: "outdoor-living", title: "Outdoor Living", division: "construction", url: "https://highlandernc.com/construction/outdoor-living" },
  { slug: "custom", title: "Custom Construction", division: "construction", url: "https://highlandernc.com/construction/custom" }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List all roofing and construction services Highlander offers, with URLs to each service page.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-service-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var towns = [
  { slug: "franklin-nc", name: "Franklin", county: "Macon" },
  { slug: "highlands-nc", name: "Highlands", county: "Macon" },
  { slug: "cashiers-nc", name: "Cashiers", county: "Jackson" },
  { slug: "sylva-nc", name: "Sylva", county: "Jackson" },
  { slug: "cullowhee-nc", name: "Cullowhee", county: "Jackson" },
  { slug: "dillsboro-nc", name: "Dillsboro", county: "Jackson" },
  { slug: "bryson-city-nc", name: "Bryson City", county: "Swain" },
  { slug: "waynesville-nc", name: "Waynesville", county: "Haywood" },
  { slug: "brevard-nc", name: "Brevard", county: "Transylvania" },
  { slug: "hendersonville-nc", name: "Hendersonville", county: "Henderson" },
  { slug: "asheville-nc", name: "Asheville", county: "Buncombe" },
  { slug: "murphy-nc", name: "Murphy", county: "Cherokee" },
  { slug: "hayesville-nc", name: "Hayesville", county: "Clay" },
  { slug: "scaly-mountain-nc", name: "Scaly Mountain", county: "Macon" },
  { slug: "otto-nc", name: "Otto", county: "Macon" },
  { slug: "lake-glenville-nc", name: "Lake Glenville", county: "Jackson" },
  { slug: "lake-toxaway-nc", name: "Lake Toxaway", county: "Transylvania" },
  { slug: "sapphire-nc", name: "Sapphire", county: "Jackson" },
  { slug: "cherokee-nc", name: "Cherokee", county: "Swain" }
];
var list_service_areas_default = defineTool3({
  name: "list_service_areas",
  title: "List service areas",
  description: "List Western North Carolina towns Highlander serves, with URLs to each town's local page.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const withUrls = towns.map((t) => ({
      ...t,
      url: `https://western-wnc-dominate.lovable.app/service-areas/${t.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(withUrls, null, 2) }],
      structuredContent: { towns: withUrls }
    };
  }
});

// src/lib/mcp/tools/search-site.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var SITEMAP_URL = "https://highlandernc.com/sitemap.xml";
var search_site_default = defineTool4({
  name: "search_site",
  title: "Search site",
  description: "Case-insensitive keyword search across Highlander's site URLs (pulled from sitemap.xml). Returns matching page URLs. Useful for finding blog posts, service pages, and town pages by topic.",
  inputSchema: {
    query: z.string().min(1).describe("Keyword or phrase to match against page URLs, e.g. 'metal roofing highlands'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results to return (default 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const res = await fetch(SITEMAP_URL, { headers: { Accept: "application/xml" } });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch sitemap: ${res.status}` }], isError: true };
    }
    const xml = await res.text();
    const urls = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1]);
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    const matches = urls.filter((u) => {
      const l = u.toLowerCase();
      return terms.every((t) => l.includes(t));
    }).slice(0, limit ?? 15);
    return {
      content: [{ type: "text", text: matches.length ? matches.join("\n") : "No matching pages." }],
      structuredContent: { query, matches }
    };
  }
});

// src/lib/mcp/tools/fetch-page.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var ALLOWED_HOST = "western-wnc-dominate.lovable.app";
var fetch_page_default = defineTool5({
  name: "fetch_page",
  title: "Fetch page",
  description: "Fetch the raw HTML of a page on the Highlander site. Only URLs on western-wnc-dominate.lovable.app are allowed. Use search_site first to find URLs.",
  inputSchema: {
    url: z2.string().url().describe("Full https URL on the Highlander site.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    let parsed;
    try {
      parsed = new URL(url);
    } catch {
      return { content: [{ type: "text", text: "Invalid URL." }], isError: true };
    }
    if (parsed.protocol !== "https:" || parsed.hostname !== ALLOWED_HOST) {
      return {
        content: [{ type: "text", text: `Only https URLs on ${ALLOWED_HOST} are allowed.` }],
        isError: true
      };
    }
    const res = await fetch(parsed.toString());
    if (!res.ok) {
      return { content: [{ type: "text", text: `Fetch failed: ${res.status}` }], isError: true };
    }
    const html = await res.text();
    const capped = html.length > 2e5 ? html.slice(0, 2e5) + "\n\n[truncated]" : html;
    return { content: [{ type: "text", text: capped }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "highlander-mcp",
  title: "Highlander Roofing & Construction",
  version: "0.1.0",
  instructions: "Tools for Highlander Roofing & Construction (Western North Carolina). Use `get_business_info` for contact details and credentials, `list_services` and `list_service_areas` for what is offered and where, `search_site` to find pages (blog posts, service pages, town pages) by keyword, and `fetch_page` to read the HTML of a specific page.",
  tools: [get_business_info_default, list_services_default, list_service_areas_default, search_site_default, fetch_page_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
