// AUTO-GENERATED by scripts/generate-blog-summaries.mjs — do not edit.
// Lightweight metadata for the homepage BlogInsights section so the full
// blogs.ts payload is only loaded on /blog and /blog/:slug routes.
export interface BlogSummary {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
}

export const blogSummaries: BlogSummary[] = [
  {
    "id": "brava-synthetic-vs-cedar-shake-vs-slate-wnc",
    "slug": "brava-synthetic-vs-cedar-shake-vs-slate-wnc",
    "title": "Brava Synthetic vs Cedar Shake vs Natural Slate for Mountain Homes",
    "excerpt": "Three ways to get a textured, high-end roof on a Western NC home — compared on weight, lifespan, maintenance, fire and what each one asks of the structure.",
    "category": "Materials",
    "date": "2026-09-15",
    "readTime": "9 min"
  },
  {
    "id": "standing-seam-vs-exposed-fastener-metal-roof-wnc",
    "slug": "standing-seam-vs-exposed-fastener-metal-roof-wnc",
    "title": "Standing Seam vs Exposed-Fastener Metal Roofing for Mountain Homes",
    "excerpt": "The two metal systems are not the same product at different prices. Here is how they differ on cost, fasteners, movement, wind, repairability and look.",
    "category": "Materials",
    "date": "2026-09-15",
    "readTime": "9 min"
  },
  {
    "id": "roof-inspection-after-storm-western-nc",
    "slug": "roof-inspection-after-storm-western-nc",
    "title": "48 to 72 Hour Roof Inspection for Western NC Homeowners",
    "excerpt": "What to inspect, photograph, and document during the first 48 to 72 hours after a Western North Carolina storm, including attic checks and insurance-ready records.",
    "category": "Inspections",
    "date": "2026-09-14",
    "readTime": "8 min"
  },
  {
    "id": "gutter-size-western-nc-mountain-homes",
    "slug": "gutter-size-western-nc-mountain-homes",
    "title": "Why 5-Inch Gutters Overflow in Western North Carolina and How to Size Them Properly",
    "excerpt": "Gutter capacity ratings assume one inch of rain per hour. Highlands is designed for 11.3. A licensed WNC contractor walks through gutter and downspout sizing using NOAA rainfall data for our towns.",
    "category": "Gutters",
    "date": "2026-09-09",
    "readTime": "9 min"
  },
  {
    "id": "wnc-storm-season-roof-damage",
    "slug": "wnc-storm-season-roof-damage",
    "title": "What a Western North Carolina Storm Season Does to Your Roof",
    "excerpt": "Wind breaks the sealant bond before it takes a shingle away, and hail either fractures the mat or it does not. A plain accounting of what a WNC summer does to a mountain roof, what you can check from the ground, and what cannot be seen without someone walking it.",
    "category": "Storm Damage",
    "date": "2026-09-04",
    "readTime": "14 min"
  },
  {
    "id": "western-north-carolina-mountain-roofing-guide",
    "slug": "western-north-carolina-mountain-roofing-guide",
    "title": "Western North Carolina Roofing Guide: Best Roofs, Costs and Mountain Home Maintenance",
    "excerpt": "Which roofing materials perform best in the Western North Carolina mountains, what replacement costs in 2026, and how to protect a mountain home from rain, moss, wind and freeze-thaw damage.",
    "category": "Materials",
    "date": "2026-08-25",
    "readTime": "18 min"
  },
  {
    "id": "pre-fall-gutter-maintenance-checklist-mountain-homeowners",
    "slug": "pre-fall-gutter-maintenance-checklist-mountain-homeowners",
    "title": "Gutter Season Is Coming: The Pre-Fall Checklist for Mountain Homeowners",
    "excerpt": "A practical guide to clearing debris, testing drainage, spotting roof-edge problems, and preparing a Western North Carolina mountain home before peak leaf fall and colder weather.",
    "category": "Maintenance",
    "date": "2026-08-19",
    "readTime": "8 min"
  },
  {
    "id": "attic-ventilation-waynesville-nc-winter",
    "slug": "attic-ventilation-waynesville-nc-winter",
    "title": "Attic Ventilation in Waynesville: The Fix Most Winter Roof Problems Start With",
    "excerpt": "Ice at the eaves, damp insulation, and premature shingle wear in Haywood County usually trace back to one thing — an unbalanced attic. Here is how to diagnose and correct it.",
    "category": "Maintenance",
    "date": "2026-08-03",
    "readTime": "6 min"
  },
  {
    "id": "roof-replacement-waynesville-nc-historic-homes",
    "slug": "roof-replacement-waynesville-nc-historic-homes",
    "title": "Roof Replacement on Waynesville's Historic Homes: Doing It Without Losing the Character",
    "excerpt": "Haywood County's older homes have complex roof lines, original detailing, and modern performance needs. Here is how we approach a replacement that respects the house.",
    "category": "Replacement",
    "date": "2026-08-02",
    "readTime": "8 min"
  },
  {
    "id": "metal-roofing-bryson-city-nc-vacation-rentals",
    "slug": "metal-roofing-bryson-city-nc-vacation-rentals",
    "title": "Metal Roofing for Bryson City Vacation Rentals: What Owners Should Know",
    "excerpt": "Bryson City rental cabins take heavy rain, heavy guest turnover, and very little downtime. Here is how standing seam metal changes the maintenance math for short-term rental owners in Swain County.",
    "category": "Materials",
    "date": "2026-08-01",
    "readTime": "7 min"
  },
  {
    "id": "highlands-nc-storm-damage-july-28-2026",
    "slug": "highlands-nc-storm-damage-july-28-2026",
    "title": "After the July 28 Storm in Highlands, NC: What Homeowners Should Check",
    "excerpt": "A Severe Thunderstorm Warning covered Highlands and southeastern Macon County on July 28, 2026. Here is a calm, practical guide to what to check from the ground, what to leave to a professional, and how to document it.",
    "category": "Storm",
    "date": "2026-07-29",
    "readTime": "9 min"
  },
  {
    "id": "home-renovation-exterior-project-cullowhee-nc",
    "slug": "home-renovation-exterior-project-cullowhee-nc",
    "title": "Planning a Home Renovation or Exterior Project in Cullowhee",
    "excerpt": "What Cullowhee, NC homeowners should know before starting a renovation or exterior project — planning, budget, and choosing the right team.",
    "category": "Construction",
    "date": "2026-07-26",
    "readTime": "8 min"
  }
];
