// AUTO-GENERATED by scripts/generate-blog-summaries.mjs — do not edit.
// Lightweight metadata for the homepage BlogInsights section so the full
// blogs.ts payload is only loaded on /blog and /blog/:slug routes.
export interface BlogSummary {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
}

export const blogSummaries: BlogSummary[] = [
  {
    "id": "highlands-nc-storm-damage-july-28-2026",
    "slug": "highlands-nc-storm-damage-july-28-2026",
    "title": "After the July 28 Storm in Highlands, NC: What Homeowners Should Check",
    "excerpt": "A Severe Thunderstorm Warning covered Highlands and southeastern Macon County on July 28, 2026. Here is a calm, practical guide to what to check from the ground, what to leave to a professional, and how to document it.",
    "category": "Storm",
    "date": "2026-07-29",
    "readTime": "9 min"
  },
  {
    "id": "storm-moisture-damage-cullowhee-nc",
    "slug": "storm-moisture-damage-cullowhee-nc",
    "title": "Storm and Moisture Damage Cullowhee Homeowners Should Watch For",
    "excerpt": "The storm and moisture damage patterns Cullowhee, NC homeowners should watch for and when to schedule a professional inspection.",
    "category": "Storm Damage",
    "date": "2026-07-26",
    "readTime": "7 min"
  },
  {
    "id": "home-renovation-exterior-project-cullowhee-nc",
    "slug": "home-renovation-exterior-project-cullowhee-nc",
    "title": "Planning a Home Renovation or Exterior Project in Cullowhee",
    "excerpt": "What Cullowhee, NC homeowners should know before starting a renovation or exterior project — planning, budget, and choosing the right team.",
    "category": "Construction",
    "date": "2026-07-26",
    "readTime": "8 min"
  },
  {
    "id": "roof-inspection-frequency-cullowhee-nc",
    "slug": "roof-inspection-frequency-cullowhee-nc",
    "title": "How Often Should Cullowhee Homeowners Inspect Their Roof?",
    "excerpt": "How often Cullowhee, NC homeowners should schedule a roof inspection and what a good inspection actually covers.",
    "category": "Inspection",
    "date": "2026-07-26",
    "readTime": "7 min"
  },
  {
    "id": "common-roofing-problems-cullowhee-nc",
    "slug": "common-roofing-problems-cullowhee-nc",
    "title": "Common Roofing Problems in Cullowhee, North Carolina",
    "excerpt": "The roofing problems we most often find on Cullowhee, NC homes and what to do about them before they get worse.",
    "category": "Repair",
    "date": "2026-07-26",
    "readTime": "7 min"
  },
  {
    "id": "roof-repair-vs-replacement-cullowhee-nc",
    "slug": "roof-repair-vs-replacement-cullowhee-nc",
    "title": "Roof Repair vs. Roof Replacement for Cullowhee Homeowners",
    "excerpt": "How Cullowhee, NC homeowners can decide between a targeted roof repair and full replacement in Jackson County's mountain climate.",
    "category": "Replacement",
    "date": "2026-07-26",
    "readTime": "7 min"
  },
  {
    "id": "storm-damage-check-sylva-nc",
    "slug": "storm-damage-check-sylva-nc",
    "title": "What to Check After a Storm in Sylva, North Carolina",
    "excerpt": "A safe, practical post storm checklist for Sylva, NC homeowners, plus when to call a local roofer for a professional evaluation.",
    "category": "Storm Damage",
    "date": "2026-07-25",
    "readTime": "7 min"
  },
  {
    "id": "exterior-repairs-before-winter-sylva-nc",
    "slug": "exterior-repairs-before-winter-sylva-nc",
    "title": "Exterior Repairs Sylva Homeowners Should Address Before Winter",
    "excerpt": "The exterior repairs Sylva, NC homeowners should address before winter to prevent water, ice, and structural damage.",
    "category": "Maintenance",
    "date": "2026-07-25",
    "readTime": "7 min"
  },
  {
    "id": "roofing-construction-contractor-sylva-nc",
    "slug": "roofing-construction-contractor-sylva-nc",
    "title": "How to Choose a Roofing and Construction Contractor in Sylva",
    "excerpt": "A practical guide for Sylva, NC homeowners on how to evaluate and choose a trustworthy local roofing and construction contractor.",
    "category": "Guides",
    "date": "2026-07-25",
    "readTime": "8 min"
  },
  {
    "id": "roof-inspection-signs-sylva-nc",
    "slug": "roof-inspection-signs-sylva-nc",
    "title": "Common Signs Your Sylva Home Needs a Roof Inspection",
    "excerpt": "The most common signs a Sylva, NC home is due for a professional roof inspection, and what a good inspection actually covers.",
    "category": "Inspection",
    "date": "2026-07-25",
    "readTime": "7 min"
  },
  {
    "id": "roof-repair-vs-replacement-sylva-nc",
    "slug": "roof-repair-vs-replacement-sylva-nc",
    "title": "Roof Repair vs. Roof Replacement for Sylva Homeowners",
    "excerpt": "How Sylva, NC homeowners can decide between a targeted roof repair and a full replacement in Jackson County's mountain climate.",
    "category": "Replacement",
    "date": "2026-07-25",
    "readTime": "8 min"
  },
  {
    "id": "property-access-terrain-mountain-construction-cashiers-nc",
    "slug": "property-access-terrain-mountain-construction-cashiers-nc",
    "title": "How Property Access and Terrain Affect Mountain Construction",
    "excerpt": "How property access, slope, and terrain shape construction scope, schedule, and budget on Cashiers, NC mountain properties.",
    "category": "Construction",
    "date": "2026-07-24",
    "readTime": "8 min"
  }
];
