// AUTO-GENERATED by scripts/generate-blog-summaries.mjs — do not edit.
// Metadata-only index of every blog post, used by internal-linking helpers so
// the full blogs.ts payload stays on /blog routes.
export interface BlogIndexEntry {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  town: string;
  /** Survivor slug when this post is folded into another (P3.5); absent otherwise. */
  canonicalTo?: string;
}

export const blogIndex: BlogIndexEntry[] = [
  {
    "slug": "half-round-vs-k-style-gutters-western-nc",
    "title": "Half-Round vs. K-Style Gutters for Western NC Homes",
    "excerpt": "Compare K-style and half-round gutters by capacity, cost, maintenance, materials, and fit for Western North Carolina mountain homes.",
    "category": "Maintenance",
    "date": "2026-10-01",
    "town": "Franklin"
  },
  {
    "slug": "chimney-flashing-repair-western-nc",
    "title": "6 Chimney Flashing Failures and the Repairs That Work",
    "excerpt": "Learn how chimney flashing systems fail, when sealant is only temporary, and what a complete Western North Carolina roof repair should include.",
    "category": "Maintenance",
    "date": "2026-09-24",
    "town": "Franklin"
  },
  {
    "slug": "dimensional-shingle-lifespan-western-nc",
    "title": "How Long Do Dimensional Shingles Last?",
    "excerpt": "Most dimensional shingle roofs last about 22 to 30 years, but Western North Carolina weather, ventilation, installation, and maintenance can shift that range.",
    "category": "Materials",
    "date": "2026-09-22",
    "town": "Franklin"
  },
  {
    "slug": "roof-flashing-leak-western-nc",
    "title": "How to Trace a Roof Flashing Leak Safely",
    "excerpt": "Learn how chimney, vent, wall, and skylight flashing leaks develop, how to document the moisture path safely, and when a Western North Carolina roof needs profe",
    "category": "Maintenance",
    "date": "2026-09-21",
    "town": "Franklin"
  },
  {
    "slug": "hail-damage-roof-western-nc",
    "title": "One Inch Hail? An Insurance Ready Roof Checklist",
    "excerpt": "How to spot hail damage by roofing material, document it safely from the ground, and build an insurance ready record for a Western North Carolina roof.",
    "category": "Storm Damage",
    "date": "2026-09-18",
    "town": "Franklin"
  },
  {
    "slug": "skylight-leak-repair-western-nc",
    "title": "Skylight Leak Repair for Western NC Mountain Homes",
    "excerpt": "Learn how to tell condensation from a skylight leak, which warning signs need professional repair, and how mountain weather affects flashing and roof openings.",
    "category": "Maintenance",
    "date": "2026-09-17",
    "town": "Franklin"
  },
  {
    "slug": "roof-valley-leak-western-nc",
    "title": "5 Causes of a Roof Valley Leak and When to Call a Pro",
    "excerpt": "Learn why roof valleys leak, how to spot warning signs safely, and when a Western North Carolina valley needs a targeted repair or full rebuild.",
    "category": "Maintenance",
    "date": "2026-09-16",
    "town": "Franklin"
  },
  {
    "slug": "brava-synthetic-vs-cedar-shake-vs-slate-wnc",
    "title": "Brava Synthetic vs Cedar Shake vs Natural Slate for Mountain Homes",
    "excerpt": "Three ways to get a textured, high-end roof on a Western NC home — compared on weight, lifespan, maintenance, fire and what each one asks of the structure.",
    "category": "Materials",
    "date": "2026-09-15",
    "town": ""
  },
  {
    "slug": "standing-seam-vs-exposed-fastener-metal-roof-wnc",
    "title": "Standing Seam vs Exposed Fastener for Mountain Homes",
    "excerpt": "Compare standing seam and exposed-fastener metal roofing by construction, maintenance, slope, wind exposure, appearance, and long-term cost for Western North Ca",
    "category": "Materials",
    "date": "2026-09-15",
    "town": "Franklin"
  },
  {
    "slug": "roof-inspection-after-storm-western-nc",
    "title": "48 to 72 Hour Roof Inspection for Western NC Homeowners",
    "excerpt": "What to inspect, photograph, and document during the first 48 to 72 hours after a Western North Carolina storm, including attic checks and insurance-ready recor",
    "category": "Inspections",
    "date": "2026-09-14",
    "town": "Franklin"
  },
  {
    "slug": "gutter-size-western-nc-mountain-homes",
    "title": "Why 5-Inch Gutters Overflow in Western North Carolina and How to Size Them Properly",
    "excerpt": "Gutter capacity ratings assume one inch of rain per hour. Highlands is designed for 11.3. A licensed WNC contractor walks through gutter and downspout sizing us",
    "category": "Gutters",
    "date": "2026-09-09",
    "town": "Highlands"
  },
  {
    "slug": "wnc-storm-season-roof-damage",
    "title": "What a Western North Carolina Storm Season Does to Your Roof",
    "excerpt": "Wind breaks the sealant bond before it takes a shingle away, and hail either fractures the mat or it does not. A plain accounting of what a WNC summer does to a",
    "category": "Storm Damage",
    "date": "2026-09-04",
    "town": "Franklin"
  },
  {
    "slug": "western-north-carolina-mountain-roofing-guide",
    "title": "Western North Carolina Roofing Guide: Best Roofs, Costs and Mountain Home Maintenance",
    "excerpt": "Which roofing materials perform best in the Western North Carolina mountains, what replacement costs in 2026, and how to protect a mountain home from rain, moss",
    "category": "Materials",
    "date": "2026-08-25",
    "town": "Highlands"
  },
  {
    "slug": "pre-fall-gutter-maintenance-checklist-mountain-homeowners",
    "title": "Gutter Season Is Coming: The Pre-Fall Checklist for Mountain Homeowners",
    "excerpt": "A practical guide to clearing debris, testing drainage, spotting roof-edge problems, and preparing a Western North Carolina mountain home before peak leaf fall ",
    "category": "Maintenance",
    "date": "2026-08-19",
    "town": "Highlands"
  },
  {
    "slug": "attic-ventilation-waynesville-nc-winter",
    "title": "Attic Ventilation in Waynesville: The Fix Most Winter Roof Problems Start With",
    "excerpt": "Ice at the eaves, damp insulation, and premature shingle wear in Haywood County usually trace back to one thing — an unbalanced attic. Here is how to diagnose a",
    "category": "Maintenance",
    "date": "2026-08-03",
    "town": "Waynesville"
  },
  {
    "slug": "roof-replacement-waynesville-nc-historic-homes",
    "title": "Roof Replacement on Waynesville's Historic Homes: Doing It Without Losing the Character",
    "excerpt": "Haywood County's older homes have complex roof lines, original detailing, and modern performance needs. Here is how we approach a replacement that respects the ",
    "category": "Replacement",
    "date": "2026-08-02",
    "town": "Waynesville"
  },
  {
    "slug": "metal-roofing-bryson-city-nc-vacation-rentals",
    "title": "Metal Roofing for Bryson City Vacation Rentals: What Owners Should Know",
    "excerpt": "Bryson City rental cabins take heavy rain, heavy guest turnover, and very little downtime. Here is how standing seam metal changes the maintenance math for shor",
    "category": "Materials",
    "date": "2026-08-01",
    "town": "Bryson City"
  },
  {
    "slug": "highlands-nc-storm-damage-july-28-2026",
    "title": "After the July 28 Storm in Highlands, NC: What Homeowners Should Check",
    "excerpt": "A Severe Thunderstorm Warning covered Highlands and southeastern Macon County on July 28, 2026. Here is a calm, practical guide to what to check from the ground",
    "category": "Storm",
    "date": "2026-07-29",
    "town": "Highlands"
  },
  {
    "slug": "home-renovation-exterior-project-cullowhee-nc",
    "title": "Planning a Home Renovation or Exterior Project in Cullowhee",
    "excerpt": "What Cullowhee, NC homeowners should know before starting a renovation or exterior project — planning, budget, and choosing the right team.",
    "category": "Construction",
    "date": "2026-07-26",
    "town": "Cullowhee"
  },
  {
    "slug": "roof-inspection-frequency-cullowhee-nc",
    "title": "How Often Should Cullowhee Homeowners Inspect Their Roof?",
    "excerpt": "How often Cullowhee, NC homeowners should schedule a roof inspection and what a good inspection actually covers.",
    "category": "Inspection",
    "date": "2026-07-26",
    "town": "Cullowhee"
  },
  {
    "slug": "roof-repair-vs-replacement-cullowhee-nc",
    "title": "Roof Repair vs. Roof Replacement for Cullowhee Homeowners",
    "excerpt": "How Cullowhee, NC homeowners can decide between a targeted roof repair and full replacement in Jackson County's mountain climate.",
    "category": "Replacement",
    "date": "2026-07-26",
    "town": "Cullowhee"
  },
  {
    "slug": "exterior-repairs-before-winter-sylva-nc",
    "title": "Exterior Repairs Sylva Homeowners Should Address Before Winter",
    "excerpt": "The exterior repairs Sylva, NC homeowners should address before winter to prevent water, ice, and structural damage.",
    "category": "Maintenance",
    "date": "2026-07-25",
    "town": "Sylva"
  },
  {
    "slug": "roofing-construction-contractor-sylva-nc",
    "title": "How to Choose a Roofing and Construction Contractor in Sylva",
    "excerpt": "A practical guide for Sylva, NC homeowners on how to evaluate and choose a trustworthy local roofing and construction contractor.",
    "category": "Guides",
    "date": "2026-07-25",
    "town": "Sylva"
  },
  {
    "slug": "roof-inspection-signs-sylva-nc",
    "title": "Common Signs Your Sylva Home Needs a Roof Inspection",
    "excerpt": "The most common signs a Sylva, NC home is due for a professional roof inspection, and what a good inspection actually covers.",
    "category": "Inspection",
    "date": "2026-07-25",
    "town": "Sylva"
  },
  {
    "slug": "roof-repair-vs-replacement-sylva-nc",
    "title": "Roof Repair vs. Roof Replacement for Sylva Homeowners",
    "excerpt": "How Sylva, NC homeowners can decide between a targeted roof repair and a full replacement in Jackson County's mountain climate.",
    "category": "Replacement",
    "date": "2026-07-25",
    "town": "Sylva"
  },
  {
    "slug": "property-access-terrain-mountain-construction-cashiers-nc",
    "title": "How Property Access and Terrain Affect Mountain Construction",
    "excerpt": "How property access, slope, and terrain shape construction scope, schedule, and budget on Cashiers, NC mountain properties.",
    "category": "Construction",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "roof-leak-causes-cashiers-nc",
    "title": "What Causes Roof Leaks in Cashiers Mountain Homes?",
    "excerpt": "The real causes of roof leaks in Cashiers, NC mountain homes and why they rarely start where the stain appears on the ceiling.",
    "category": "Repair",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "fall-winter-preparation-cashiers-nc",
    "title": "How to Prepare a Cashiers Home for Fall and Winter",
    "excerpt": "A practical fall and winter preparation checklist for Cashiers, NC mountain homes, including roofs, gutters, drainage, and exterior systems.",
    "category": "Maintenance",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "mountain-construction-project-cashiers-nc",
    "title": "Planning a Construction Project on a Mountain Property in Cashiers",
    "excerpt": "How to plan a construction project on a Cashiers, NC mountain property — site, weather, permits, and choosing the right team.",
    "category": "Construction",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "roof-inspection-cashiers-nc",
    "title": "What to Look for During a Cashiers Roof Inspection",
    "excerpt": "What a real roof inspection covers on a Cashiers, NC mountain home and how the report helps you plan the next step.",
    "category": "Inspection",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "moisture-tree-coverage-roofs-cashiers-nc",
    "title": "How Moisture and Tree Coverage Affect Roofs in Cashiers",
    "excerpt": "How moisture and mature tree cover in Cashiers, NC shape roof life, gutter maintenance, and long term protection.",
    "category": "Maintenance",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "metal-roofing-vs-shingles-cashiers-nc",
    "title": "Metal Roofing vs. Shingles for Cashiers Mountain Properties",
    "excerpt": "A Cashiers, NC roofer's honest comparison of standing seam metal and quality shingle systems on mountain properties at elevation.",
    "category": "Materials",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "second-home-roofing-cashiers-nc",
    "title": "Roofing Considerations for Second Homes in Cashiers",
    "excerpt": "What second home owners in Cashiers, NC should know about roofing, inspections, and protecting a mountain property between visits.",
    "category": "Maintenance",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "roof-repair-vs-replacement-cashiers-nc",
    "title": "Roof Repair vs. Roof Replacement: How Cashiers Homeowners Know the Difference",
    "excerpt": "How Cashiers, NC homeowners can tell when a targeted roof repair is enough and when a full replacement protects the home better.",
    "category": "Replacement",
    "date": "2026-07-24",
    "town": "Cashiers"
  },
  {
    "slug": "metal-roofing-cost-wnc",
    "title": "Metal Roofing Cost in Western NC: Standing Seam vs. Exposed Fastener",
    "excerpt": "A regional pricing guide to metal roof cost in Western North Carolina — how standing seam and exposed fastener systems compare, and what elevation, wind load, a",
    "category": "Cost",
    "date": "2026-07-24",
    "town": ""
  },
  {
    "slug": "gutter-drainage-roof-problems-franklin-nc",
    "title": "Gutter, Drainage, and Roof Problems Franklin Homeowners Should Not Ignore",
    "excerpt": "The gutter, drainage, and roof issues Franklin, NC homeowners should address quickly to prevent structural and water damage.",
    "category": "Maintenance",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "home-addition-renovation-franklin-nc",
    "title": "Planning a Home Addition or Renovation in Franklin",
    "excerpt": "What Franklin, NC homeowners should know before starting a home addition or renovation — planning, contractors, budget, and timing.",
    "category": "Construction",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "how-to-choose-roofing-contractor-franklin-nc",
    "title": "How to Choose a Roofing Contractor in Franklin, NC",
    "excerpt": "A practical guide for Franklin, NC homeowners on how to evaluate and choose a trustworthy local roofing contractor.",
    "category": "Guides",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "best-time-to-replace-roof-franklin-nc",
    "title": "When Is the Best Time to Replace a Roof in Franklin?",
    "excerpt": "How Franklin, NC homeowners can time a roof replacement around weather, schedule, budget, and long term protection.",
    "category": "Replacement",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "metal-roof-maintenance-franklin-nc",
    "title": "Metal Roof Maintenance for Franklin Homeowners",
    "excerpt": "A practical maintenance guide for Franklin, NC homeowners with standing seam or exposed fastener metal roofs.",
    "category": "Maintenance",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "common-roofing-problems-western-nc",
    "title": "Why Roofs Fail Early in Western North Carolina",
    "excerpt": "Flashing, vent boots, debris, wind uplift, loose fasteners, drainage and underlayment — the seven failures behind almost every early roof replacement here.",
    "category": "Repair",
    "date": "2026-07-23",
    "town": ""
  },
  {
    "slug": "roof-inspection-frequency-franklin-nc",
    "title": "How Often Should Franklin Homeowners Schedule a Roof Inspection?",
    "excerpt": "How often Franklin, NC homeowners should schedule a roof inspection, what a real inspection includes, and how it protects your home long term.",
    "category": "Inspection",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "small-exterior-repairs-franklin-nc",
    "title": "Five Small Exterior Repairs That Can Prevent Major Damage in Franklin",
    "excerpt": "Five inexpensive exterior repairs that Franklin, NC homeowners can address early to avoid costly water, structural, and roofing damage later.",
    "category": "Maintenance",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "roof-repair-vs-replacement-franklin-nc",
    "title": "Roof Repair vs. Roof Replacement: How Franklin Homeowners Know the Difference",
    "excerpt": "A local roofer's guide to deciding when a Franklin, NC home needs a targeted roof repair and when full replacement is the smarter long-term move.",
    "category": "Replacement",
    "date": "2026-07-23",
    "town": "Franklin"
  },
  {
    "slug": "exterior-maintenance-checklist-highlands-nc",
    "title": "Exterior Maintenance Checklist for Highlands Mountain Homes",
    "excerpt": "A season by season exterior maintenance checklist for Highlands, NC mountain homes — roof, gutters, siding, drainage, and more.",
    "category": "Maintenance",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "construction-project-highlands-nc",
    "title": "What to Know Before Starting a Construction Project in Highlands",
    "excerpt": "Planning a construction project in Highlands, NC? Here is what mountain homeowners should understand about site, weather, permits, and contractors.",
    "category": "Construction",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "tree-coverage-roofs-gutters-highlands-nc",
    "title": "How Tree Coverage Affects Roofs and Gutters in Highlands",
    "excerpt": "Tree cover is part of what makes Highlands beautiful — and part of what wears out roofs and gutters. Here is how to manage it.",
    "category": "Maintenance",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "common-roof-leak-locations-highlands-nc",
    "title": "Common Roof Leak Locations in Highlands Mountain Homes",
    "excerpt": "The places we actually find roof leaks on Highlands, NC homes and why mountain conditions make certain spots more vulnerable than others.",
    "category": "Repair",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "second-home-maintenance-highlands-nc",
    "title": "How Seasonal Homeowners Can Protect Their Highlands Property",
    "excerpt": "A practical maintenance plan for second home and seasonal owners in Highlands, NC — so your mountain property is ready every time you arrive.",
    "category": "Maintenance",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "metal-roofing-vs-shingles-highlands-nc",
    "title": "Metal Roofing vs. Shingles for Highlands Mountain Homes",
    "excerpt": "A local roofer's comparison of standing seam metal and quality shingle systems on Highlands, NC homes — cost, life, style, and mountain performance.",
    "category": "Materials",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "mountain-weather-roofs-highlands-nc",
    "title": "How Mountain Weather Affects Roofs in Highlands, North Carolina",
    "excerpt": "Elevation, rainfall, wind, and freeze cycles shape how every roof in Highlands ages. Here is how mountain weather actually affects your roof.",
    "category": "Weather",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "roof-inspection-highlands-nc",
    "title": "The Homeowner's Guide to Roof Inspections in Highlands, NC",
    "excerpt": "What a real roof inspection covers on a Highlands home, when to schedule one, and how to use the report to protect your property.",
    "category": "Inspection",
    "date": "2026-07-22",
    "town": "Highlands"
  },
  {
    "slug": "roof-repair-vs-roof-replacement-highlands-nc",
    "title": "Roof Repair vs. Roof Replacement: How Homeowners in Highlands Know the Difference",
    "excerpt": "A local roofer's guide to deciding when a Highlands, NC home needs a focused roof repair and when full replacement is the smarter long-term move.",
    "category": "Replacement",
    "date": "2026-07-21",
    "town": "Highlands"
  },
  {
    "slug": "tree-cover-rain-elevation-affect-roofs-wnc",
    "title": "How Tree Cover, Rain, and Elevation Affect Roofs in WNC",
    "excerpt": "The three biggest environmental factors on WNC roofs — tree cover, rainfall, and elevation — and how they shape maintenance.",
    "category": "Seasonal",
    "date": "2026-07-20",
    "town": "Highlands"
  },
  {
    "slug": "best-time-of-year-replace-roof-western-north-carolina",
    "title": "Best Time of Year to Replace a Roof in Western North Carolina",
    "excerpt": "When to schedule a roof replacement in Western NC — weather windows, lead times, and planning ahead.",
    "category": "Seasonal",
    "date": "2026-07-20",
    "town": ""
  },
  {
    "slug": "roofing-mountain-homes-lake-glenville-scaly-mountain",
    "title": "Roofing for Mountain Homes Near Lake Glenville and Scaly Mountain",
    "excerpt": "Roofing considerations for homes near Lake Glenville and Scaly Mountain — elevation, wind, and lake-effect weather.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Lake Glenville"
  },
  {
    "slug": "roofing-vacation-second-homes-highlands-cashiers",
    "title": "Roofing for Vacation Homes and Second Homes in Highlands and Cashiers",
    "excerpt": "What second-home owners in Highlands and Cashiers should know about roof maintenance, monitoring, and long-distance communication.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Highlands"
  },
  {
    "slug": "roofing-construction-services-western-north-carolina",
    "title": "Roofing and Construction Services Across Western North Carolina",
    "excerpt": "An overview of Highlander's roofing and construction services across Western North Carolina — one team, roof to remodel.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Highlands"
  },
  {
    "slug": "roofing-contractor-sylva-nc-roofing-gutters-repairs",
    "title": "Roofing Contractor in Sylva, NC: Roofing, Gutters, and Repairs",
    "excerpt": "Roofing, gutters, and repair services for Sylva, NC homeowners — what Highlander handles across Jackson County.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Sylva"
  },
  {
    "slug": "roofing-company-cashiers-nc-choosing-contractor",
    "title": "Roofing Company in Cashiers, NC: Choosing the Right Contractor",
    "excerpt": "How Cashiers, NC homeowners can evaluate roofing contractors — credentials, process, and mountain-climate fit.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Cashiers"
  },
  {
    "slug": "roofing-company-highlands-nc-local-factors",
    "title": "Roofing Company in Highlands, NC: Local Factors That Matter",
    "excerpt": "What sets a real Highlands, NC roofing company apart — elevation experience, access, and mountain-climate detail.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Highlands"
  },
  {
    "slug": "roofing-company-franklin-nc-what-to-look-for",
    "title": "Roofing Company in Franklin, NC: What to Look for Before Hiring",
    "excerpt": "What Franklin, NC homeowners should look for when hiring a roofing company — credentials, process, and local knowledge.",
    "category": "Local",
    "date": "2026-07-20",
    "town": "Franklin"
  },
  {
    "slug": "decks-porches-outdoor-spaces-mountain-weather",
    "title": "Decks, Porches, and Outdoor Living Spaces for Mountain Weather",
    "excerpt": "How to plan decks, porches, and outdoor spaces that hold up to Western NC mountain weather — freeze/thaw, rain, and wind.",
    "category": "Outdoor Living",
    "date": "2026-07-15",
    "town": "Franklin"
  },
  {
    "slug": "covered-porches-patios-western-nc-considerations",
    "title": "Covered Porches and Patios in Western NC: What to Consider",
    "excerpt": "Covered porches and patios extend the usable season for Western NC homes — here's what to think through before building.",
    "category": "Outdoor Living",
    "date": "2026-07-15",
    "town": ""
  },
  {
    "slug": "outdoor-living-cashiers-nc-mountain-homes",
    "title": "Outdoor Living in Cashiers, NC: Planning Spaces for Mountain Homes",
    "excerpt": "How to plan porches, patios, and outdoor living spaces for Cashiers, NC mountain homes — with view, weather, and daily use in mind.",
    "category": "Outdoor Living",
    "date": "2026-07-15",
    "town": "Cashiers"
  },
  {
    "slug": "outdoor-living-highlands-nc-porches-patios",
    "title": "Outdoor Living in Highlands, NC: Porches, Patios, and Mountain Views",
    "excerpt": "Planning porches, patios, and outdoor living spaces on Highlands, NC mountain homes — sightlines, weather, and structure.",
    "category": "Outdoor Living",
    "date": "2026-07-15",
    "town": "Highlands"
  },
  {
    "slug": "design-consultation-agreement-construction-project",
    "title": "How a Design & Consultation Agreement Helps Plan a Construction Project",
    "excerpt": "The Design & Consultation Agreement defines scope, drawings, and design fees before construction pricing — here's how it works.",
    "category": "Design",
    "date": "2026-07-15",
    "town": ""
  },
  {
    "slug": "design-services-vs-build-ready-plans",
    "title": "Design Services vs. Build-Ready Plans: What Highlander Needs to Start",
    "excerpt": "What's the difference between design services and build-ready plans — and what Highlander needs to price and build your Western NC project.",
    "category": "Design",
    "date": "2026-07-15",
    "town": ""
  },
  {
    "slug": "home-addition-without-plans-western-nc",
    "title": "What If I Want a Home Addition but Do Not Have Plans Yet?",
    "excerpt": "Most Western NC homeowners start an addition without plans. Here's how Highlander's design team turns an idea into build-ready drawings.",
    "category": "Design",
    "date": "2026-07-15",
    "town": ""
  },
  {
    "slug": "construction-services-cashiers-nc-additions-porches",
    "title": "Construction Services in Cashiers, NC: Planning Additions, Porches, and Outdoor Spaces",
    "excerpt": "Planning an addition, porch, or outdoor space in Cashiers, NC? Here's how Highlander scopes and designs mountain construction projects.",
    "category": "Construction",
    "date": "2026-07-15",
    "town": "Cashiers"
  },
  {
    "slug": "construction-services-highlands-nc-mountain-homes",
    "title": "Construction Services in Highlands, NC for Mountain Homes",
    "excerpt": "How Highlander approaches additions, porches, and construction projects on Highlands, NC mountain homes at elevation.",
    "category": "Construction",
    "date": "2026-07-15",
    "town": "Highlands"
  },
  {
    "slug": "construction-services-franklin-nc",
    "title": "Construction Services in Franklin, NC: What to Know Before Starting a Project",
    "excerpt": "A practical guide to planning a construction project in Franklin, NC — from first idea to Design & Consultation Agreement.",
    "category": "Construction",
    "date": "2026-07-15",
    "town": "Franklin"
  },
  {
    "slug": "fall-roof-gutter-maintenance-before-winter-mountains",
    "title": "Fall Roof and Gutter Maintenance Tips Before Winter in the Mountains",
    "excerpt": "The fall maintenance checklist that keeps WNC mountain roofs and gutters ready for winter freeze/thaw, snow, and ice.",
    "category": "Maintenance",
    "date": "2026-07-10",
    "town": ""
  },
  {
    "slug": "skylight-leaks-roof-or-skylight-wnc",
    "title": "Skylight Leaks: Roof Problem or Skylight Problem?",
    "excerpt": "How to diagnose a leaky skylight on a Western NC mountain home — and why the skylight is often not the actual problem.",
    "category": "Maintenance",
    "date": "2026-07-10",
    "town": ""
  },
  {
    "slug": "skylight-replacement-wnc",
    "title": "Skylight Replacement: When Repairs Are Not Enough",
    "excerpt": "How to tell when a WNC skylight is past repair — and what a proper replacement should include to prevent future leaks.",
    "category": "Materials",
    "date": "2026-07-10",
    "town": ""
  },
  {
    "slug": "velux-skylights-mountain-homes",
    "title": "Velux Skylights for Mountain Homes: Light, Ventilation, and Planning",
    "excerpt": "Why Velux is the dominant skylight choice for Western NC mountain homes — light quality, ventilation options, and planning considerations.",
    "category": "Materials",
    "date": "2026-07-10",
    "town": ""
  },
  {
    "slug": "skylight-installation-western-nc",
    "title": "Skylight Installation in Western NC: What Homeowners Should Consider",
    "excerpt": "Planning a skylight install on a Western NC mountain home — placement, product choice, and the details that keep them leak-free long-term.",
    "category": "Materials",
    "date": "2026-07-10",
    "town": ""
  },
  {
    "slug": "how-gutters-protect-home-wnc",
    "title": "How Gutters Help Protect Roofs, Siding, Foundations, and Outdoor Living Areas",
    "excerpt": "Gutters do more than move rainwater — here's how a well-designed WNC system protects the whole home, from roof edge to foundation.",
    "category": "Maintenance",
    "date": "2026-07-09",
    "town": ""
  },
  {
    "slug": "gutter-guards-worth-it-western-nc",
    "title": "Gutter Guards in Western NC: Are They Worth It for Mountain Homes?",
    "excerpt": "An honest look at gutter guards for Western NC mountain homes — where they earn their cost and where they don't.",
    "category": "Maintenance",
    "date": "2026-07-09",
    "town": ""
  },
  {
    "slug": "gutter-replacement-cashiers-nc",
    "title": "Gutter Replacement in Cashiers, NC: Signs It Is Time to Upgrade",
    "excerpt": "How to tell when Cashiers, NC gutters are past repair — and what a proper replacement should include.",
    "category": "Maintenance",
    "date": "2026-07-09",
    "town": "Cashiers"
  },
  {
    "slug": "seamless-gutters-highlands-nc",
    "title": "Seamless Gutters in Highlands, NC: Protecting Mountain Homes From Heavy Rain",
    "excerpt": "How seamless aluminum gutters protect Highlands, NC mountain homes from the region's heavy annual rainfall and heavy tree cover.",
    "category": "Maintenance",
    "date": "2026-07-09",
    "town": "Highlands"
  },
  {
    "slug": "gutter-installation-franklin-nc",
    "title": "Gutter Installation in Franklin, NC: Why Water Management Matters",
    "excerpt": "Why proper gutter installation matters on Franklin, NC homes — and how a well-designed system protects roofs, siding, and foundations.",
    "category": "Maintenance",
    "date": "2026-07-09",
    "town": "Franklin"
  },
  {
    "slug": "metal-vs-shingle-roof-franklin-highlands-cashiers",
    "title": "Metal Roof vs. Shingle Roof in Franklin, Highlands, and Cashiers",
    "excerpt": "A side-by-side comparison of metal and shingle roofs across Franklin, Highlands, and Cashiers — with the trade-offs each town brings.",
    "category": "Materials",
    "date": "2026-07-08",
    "town": "Highlands"
  },
  {
    "slug": "metal-roofing-highlands-nc-benefits",
    "title": "Metal Roofing in Highlands, NC: Benefits for Rain, Wind, and Elevation",
    "excerpt": "Why standing seam metal is one of the strongest roofing options for Highlands, NC homes at 4,000+ feet.",
    "category": "Materials",
    "date": "2026-07-08",
    "town": "Highlands"
  },
  {
    "slug": "metal-roofing-western-nc-mountain-home",
    "title": "Metal Roofing in Western NC: Is It Right for Your Mountain Home?",
    "excerpt": "An honest look at metal roofing for Western NC mountain homes — where it shines, where it doesn't, and what to consider before choosing it.",
    "category": "Materials",
    "date": "2026-07-08",
    "town": ""
  },
  {
    "slug": "roof-repair-vs-replacement-wnc",
    "title": "Roof Repair vs. Roof Replacement: How to Make the Right Choice",
    "excerpt": "A clear framework for Western NC homeowners deciding between roof repair and full replacement — with the questions that actually matter.",
    "category": "Replacement",
    "date": "2026-07-08",
    "town": ""
  },
  {
    "slug": "roof-lifespan-mountain-home-wnc",
    "title": "How Long Does a Roof Last on a Mountain Home in WNC?",
    "excerpt": "Real-world roof lifespans for Western NC mountain homes across shingles, metal, and specialty systems — with the caveats that matter.",
    "category": "Materials",
    "date": "2026-07-07",
    "town": ""
  },
  {
    "slug": "roof-replacement-cost-factors-western-nc",
    "title": "Roof Replacement Cost Factors in Western North Carolina",
    "excerpt": "The real factors that shape a WNC roof replacement estimate — and why flat, published pricing rarely reflects actual mountain conditions.",
    "category": "Cost",
    "date": "2026-07-07",
    "town": ""
  },
  {
    "slug": "roof-replacement-sylva-nc",
    "title": "Roof Replacement in Sylva, NC: Materials, Timing, and Process",
    "excerpt": "Sylva, NC roof replacement guide — how to pick the right material, when to schedule, and what the process looks like on Jackson County homes.",
    "category": "Replacement",
    "date": "2026-07-07",
    "town": "Sylva"
  },
  {
    "slug": "roof-replacement-cashiers-nc",
    "title": "Roof Replacement in Cashiers, NC: What Homeowners Should Expect",
    "excerpt": "What a Cashiers, NC roof replacement actually involves — timeline, materials, and what makes plateau projects different.",
    "category": "Replacement",
    "date": "2026-07-07",
    "town": "Cashiers"
  },
  {
    "slug": "roof-replacement-highlands-nc",
    "title": "Roof Replacement in Highlands, NC: Planning for Mountain Weather",
    "excerpt": "A guide to planning a Highlands, NC roof replacement around mountain weather, elevation, and material choice.",
    "category": "Replacement",
    "date": "2026-07-07",
    "town": "Highlands"
  },
  {
    "slug": "roof-replacement-franklin-nc",
    "title": "Roof Replacement in Franklin, NC: When Repair Is No Longer Enough",
    "excerpt": "How Franklin, NC homeowners can tell when a roof has passed the repair stage — and what a proper replacement project looks like.",
    "category": "Replacement",
    "date": "2026-07-07",
    "town": "Franklin"
  },
  {
    "slug": "spring-roof-maintenance-western-nc",
    "title": "Spring Roof Maintenance Tips for Western NC Homes",
    "excerpt": "A practical spring maintenance checklist for Western NC roofs after a mountain winter of freeze, thaw, wind, and debris.",
    "category": "Maintenance",
    "date": "2026-07-06",
    "town": ""
  },
  {
    "slug": "heavy-rain-roofs-gutters-western-nc",
    "title": "How Heavy Rain Impacts Roofs and Gutters in Western NC",
    "excerpt": "Western NC gets some of the highest annual rainfall in the eastern US. Here's how that affects your roof, gutters, and long-term maintenance planning.",
    "category": "Maintenance",
    "date": "2026-07-06",
    "town": ""
  },
  {
    "slug": "emergency-vs-scheduled-roof-repair-wnc",
    "title": "Emergency Roof Repair vs. Scheduled Roof Repair: What Western NC Homeowners Should Know",
    "excerpt": "How Western NC homeowners can tell whether a roof issue is an urgent call or a scheduled repair — and how each is handled.",
    "category": "Maintenance",
    "date": "2026-07-06",
    "town": ""
  },
  {
    "slug": "roof-leak-repair-western-nc",
    "title": "Roof Leak Repair in Western North Carolina: Causes, Warning Signs, and Next Steps",
    "excerpt": "The most common causes of roof leaks on Western NC mountain homes, and how to plan repair without over- or under-scoping.",
    "category": "Maintenance",
    "date": "2026-07-06",
    "town": ""
  },
  {
    "slug": "water-through-ceiling-western-nc",
    "title": "What to Do When Water Is Coming Through Your Ceiling in Western NC",
    "excerpt": "Immediate steps for Western NC homeowners when water starts coming through the ceiling — protect your home first, then diagnose the roof.",
    "category": "Storm",
    "date": "2026-07-05",
    "town": ""
  },
  {
    "slug": "roof-repair-sylva-nc",
    "title": "Roof Repair in Sylva, NC: Signs Your Roof Needs Attention",
    "excerpt": "The signs Sylva, NC homeowners should watch for on aging Jackson County roofs — from granule loss to fascia rot.",
    "category": "Maintenance",
    "date": "2026-07-05",
    "town": "Sylva"
  },
  {
    "slug": "roof-repair-cashiers-nc",
    "title": "Roof Repair in Cashiers, NC: Leaks, Storm Damage, and When to Call",
    "excerpt": "How Cashiers, NC homeowners can tell the difference between a minor repair and storm damage that needs immediate attention.",
    "category": "Storm",
    "date": "2026-07-05",
    "town": "Cashiers"
  },
  {
    "slug": "roof-repair-highlands-nc",
    "title": "Roof Repair in Highlands, NC: Common Issues for Mountain Homes",
    "excerpt": "The most common roof issues on Highlands, NC mountain homes — and how to plan repairs around elevation, wind, and freeze/thaw cycles.",
    "category": "Maintenance",
    "date": "2026-07-05",
    "town": "Highlands"
  },
  {
    "slug": "roof-repair-franklin-nc",
    "title": "Roof Repair in Franklin, NC: What Homeowners Should Know Before Small Problems Grow",
    "excerpt": "A practical guide to spotting and addressing small roof problems in Franklin, NC before they turn into full replacements.",
    "category": "Maintenance",
    "date": "2026-07-05",
    "town": "Franklin"
  },
  {
    "slug": "mountain-roof-ventilation-science",
    "title": "The Science of Mountain Roof Ventilation: Why standard codes aren't enough",
    "excerpt": "Deep snow and high humidity create unique ventilation challenges. Learn how we prevent mold and ice dams with better airflow design.",
    "category": "Materials",
    "date": "2026-07-01",
    "town": ""
  },
  {
    "slug": "guest-suite-vs-mother-in-law-flat",
    "title": "Guest Suite vs. Mother-in-Law Flat: Design Differences for WNC Homes",
    "excerpt": "Planning for long-term visitors? Learn the layout differences between a temporary guest wing and a full secondary living suite.",
    "category": "Design",
    "date": "2026-06-26",
    "town": ""
  },
  {
    "slug": "protecting-your-view-window-layout-strategies",
    "title": "Protecting Your View: Layout Strategies for Window Placement",
    "excerpt": "You bought your WNC home for the view. Learn how to plan additions that enhance, not block, your mountain horizon.",
    "category": "Design",
    "date": "2026-06-22",
    "town": ""
  },
  {
    "slug": "designing-for-drainage-foundation-safety",
    "title": "Designing for Drainage: Why Hardscape Planning Matters for Foundation Safety",
    "excerpt": "Your deck or addition is only as safe as the ground beneath it. Learn why water management is a design priority.",
    "category": "Construction",
    "date": "2026-06-18",
    "town": ""
  },
  {
    "slug": "transforming-screened-porch-sunroom",
    "title": "Case Study: Transforming a Screened Porch into a Year-Round Sunroom",
    "excerpt": "Learn the structural and layout steps needed to turn a seasonal space into a heated living area.",
    "category": "Construction",
    "date": "2026-06-14",
    "town": ""
  },
  {
    "slug": "budgeting-for-preconstruction-planning",
    "title": "Budgeting for Pre-Construction: Why Planning Saves 15% on Build Costs",
    "excerpt": "Investing in planning prevents costly mistakes during construction. Learn the ROI of the Design phase.",
    "category": "Cost",
    "date": "2026-06-10",
    "town": ""
  },
  {
    "slug": "modern-mountain-design-trends-2026",
    "title": "Design Trends: Modern Mountain Rusticity in 2026",
    "excerpt": "What's shaping WNC home design this year? From mixed-material exteriors to floor plans that prioritize 'wellness' spaces.",
    "category": "Design",
    "date": "2026-06-05",
    "town": ""
  },
  {
    "slug": "structural-feasibility-second-story-wnc",
    "title": "Structural Feasibility: Can Your WNC Home Support a Second Story?",
    "excerpt": "Thinking of building up? Learn how we evaluate foundations and framing to determine if a vertical addition is possible.",
    "category": "Design",
    "date": "2026-06-02",
    "town": ""
  },
  {
    "slug": "outdoor-kitchen-layouts-high-elevation",
    "title": "Outdoor Kitchen Layouts Built for High Elevation",
    "excerpt": "Designing an outdoor kitchen at 4,000 feet requires different materials and layout logic than a lowland patio.",
    "category": "Construction",
    "date": "2026-05-28",
    "town": "Highlands"
  },
  {
    "slug": "permitting-additions-macon-vs-jackson-county",
    "title": "Permitting for Additions: Macon vs. Jackson County",
    "excerpt": "The rules change at the county line. A guide to building codes and permit timelines in Franklin, Highlands, and Sylva.",
    "category": "Local",
    "date": "2026-05-25",
    "town": "Franklin"
  },
  {
    "slug": "maximizing-natural-light-skylight-strategies",
    "title": "Maximizing Natural Light: Skylight and Floor-Plan Strategies",
    "excerpt": "Mountain homes often have deep porches that darken the interior. Learn how to pull light back into your living space.",
    "category": "Design",
    "date": "2026-05-22",
    "town": "Franklin"
  },
  {
    "slug": "plan-multi-phase-home-addition-wnc",
    "title": "How to Plan a Multi-Phase Home Addition in WNC",
    "excerpt": "Breaking a large project into manageable phases requires master planning. Learn how to sequence your addition for budget and lifestyle.",
    "category": "Design",
    "date": "2026-05-18",
    "town": ""
  },
  {
    "slug": "terrain-responsive-floor-plans-wnc",
    "title": "Terrain-Responsive Floor Plans for Highlands and Cashiers",
    "excerpt": "Building on a cliff? Learn how to plan floor plans that work with extreme slopes and rock formations.",
    "category": "Construction",
    "date": "2026-05-12",
    "town": "Highlands"
  },
  {
    "slug": "construction-scope-development-guide",
    "title": "Scope Development: How to Define Your Project Before It Starts",
    "excerpt": "Learn the step-by-step process of turning your ideas into a buildable construction scope of work.",
    "category": "Construction",
    "date": "2026-05-05",
    "town": "Highlands"
  },
  {
    "slug": "mountain-room-addition-trends",
    "title": "The Rise of the 'Mountain Room' Addition in WNC",
    "excerpt": "Discover the most popular room addition type for Highlands and Cashiers homeowners in 2026.",
    "category": "Construction",
    "date": "2026-04-25",
    "town": ""
  },
  {
    "slug": "choosing-materials-for-high-elevation",
    "title": "Choosing Materials for High-Elevation Builds",
    "excerpt": "UV, wind, and ice change the rules for material selection. Learn what to pick for homes above 3,500 feet.",
    "category": "Materials",
    "date": "2026-04-20",
    "town": ""
  },
  {
    "slug": "floor-plan-modernization-older-homes",
    "title": "Modernizing Older WNC Floor Plans for Today's Lifestyle",
    "excerpt": "How to transform a traditional mountain home layout into a bright, open space without losing its character.",
    "category": "Construction",
    "date": "2026-04-18",
    "town": ""
  },
  {
    "slug": "wnc-construction-permitting-guide",
    "title": "Navigating WNC Construction Permits: Macon, Jackson, and Beyond",
    "excerpt": "Don't let paperwork stall your project. A guide to permitting for additions and renovations in Western North Carolina.",
    "category": "Construction",
    "date": "2026-04-12",
    "town": ""
  },
  {
    "slug": "deck-vs-porch-planning-wnc",
    "title": "Deck vs. Screened Porch: Which Layout is Right for You?",
    "excerpt": "Trying to decide how to expand your outdoor space? Compare the layout benefits of open decks and covered porches.",
    "category": "Construction",
    "date": "2026-04-10",
    "town": ""
  },
  {
    "slug": "mountain-roofing-maintenance-checklist",
    "title": "The Ultimate Mountain Roofing Maintenance Checklist",
    "excerpt": "Living at elevation means different wear patterns. Use this checklist to stay ahead of mountain-specific roofing issues.",
    "category": "Maintenance",
    "date": "2026-04-05",
    "town": ""
  },
  {
    "slug": "kitchen-layout-trends-mountain-homes",
    "title": "Kitchen Layout Trends for Modern Mountain Living",
    "excerpt": "From open-concept 'Great Rooms' to hidden pantries. Discover how to plan a kitchen that works for WNC life.",
    "category": "Construction",
    "date": "2026-04-02",
    "town": ""
  },
  {
    "slug": "phased-renovation-planning-wnc",
    "title": "The Homeowner's Guide to Phased Renovation Planning",
    "excerpt": "Want to renovate but can't do it all at once? Learn how to build a multi-year master plan for your WNC home.",
    "category": "Construction",
    "date": "2026-03-20",
    "town": ""
  },
  {
    "slug": "planning-your-mountain-home-layout",
    "title": "Planning Your Mountain Home Layout: Flow, Views, and Function",
    "excerpt": "A guide to project planning and layout design for additions and renovations in Western North Carolina.",
    "category": "Construction",
    "date": "2026-03-20",
    "town": ""
  },
  {
    "slug": "mountain-porch-deck-design-wnc",
    "title": "Mountain Porch & Deck Design: Maximize Your WNC View",
    "excerpt": "How to choose the right orientation, materials, and layout for outdoor living spaces that survive mountain weather.",
    "category": "Construction",
    "date": "2026-03-15",
    "town": ""
  },
  {
    "slug": "cost-saving-layout-tips-wnc",
    "title": "Cost-Saving Layout Tips for Your Next Home Improvement",
    "excerpt": "How intelligent project planning can save you thousands in construction costs before the first hammer swings.",
    "category": "Cost",
    "date": "2026-03-12",
    "town": ""
  },
  {
    "slug": "project-spotlight-standing-seam-highlands-estate",
    "title": "Project Spotlight: Standing Seam Metal Roof on a Highlands Estate",
    "excerpt": "A deep look at our most complex metal roofing project — 3,200 sq ft, 12/12 pitch, 8 gable intersections, and custom-fabricated panels.",
    "category": "Spotlight",
    "date": "2026-03-10",
    "town": "Highlands"
  },
  {
    "slug": "master-suite-layouts-wnc",
    "title": "Optimizing Your Master Suite Layout for Mountain Living",
    "excerpt": "Thinking about a master wing addition? Here is how to plan the perfect flow between sleep, storage, and views.",
    "category": "Construction",
    "date": "2026-03-05",
    "town": ""
  },
  {
    "slug": "why-hire-one-company-roof-and-construction",
    "title": "Why Hiring One Company for Roofing and Construction Makes Sense",
    "excerpt": "Coordinating separate roofing and construction contractors creates problems. Here's why a single team delivers better results.",
    "category": "Construction",
    "date": "2026-03-01",
    "town": ""
  },
  {
    "slug": "mountain-home-addition-planning",
    "title": "Planning a Home Addition in WNC: Technical Hurdles to Solve First",
    "excerpt": "Building on a mountain slope requires more than just a footprint. Learn the unique engineering and permitting steps for WNC additions.",
    "category": "Construction",
    "date": "2026-03-01",
    "town": ""
  },
  {
    "slug": "understanding-roof-ventilation-mountain-homes",
    "title": "Understanding Roof Ventilation for Mountain Homes in WNC",
    "excerpt": "Proper ventilation prevents ice dams, reduces energy costs, and extends roof life. Here's how it works at elevation.",
    "category": "Materials",
    "date": "2026-02-25",
    "town": ""
  },
  {
    "slug": "outdoor-living-trends-wnc",
    "title": "Mountain-Grade Outdoor Living: Decks, Porches & Pergolas in 2026",
    "excerpt": "The best outdoor spaces in WNC prioritize three things: view, weather protection, and material longevity. Explore what's working now.",
    "category": "Construction",
    "date": "2026-02-25",
    "town": ""
  },
  {
    "slug": "planning-home-addition-western-nc",
    "title": "Planning a Home Addition in Western NC: What Mountain Homeowners Need to Know",
    "excerpt": "Building an addition in the mountains involves terrain, weather, and structural factors that flatland builders don't consider.",
    "category": "Construction",
    "date": "2026-02-20",
    "town": "Franklin"
  },
  {
    "slug": "why-design-planning-matters",
    "title": "Why 'Design' is the Secret to a Stress-Free Build",
    "excerpt": "Most construction delays happen because of poor planning, not poor building. Discover the Highlander pre-construction process.",
    "category": "Construction",
    "date": "2026-02-18",
    "town": ""
  },
  {
    "slug": "how-much-does-roof-cost-highlands-nc",
    "title": "How Much Does a New Roof Cost in Highlands, NC?",
    "excerpt": "A breakdown of real roofing costs for Highlands homeowners — from materials to labor to elevation factors that affect your bottom line.",
    "category": "Cost",
    "date": "2026-02-15",
    "town": "Highlands"
  },
  {
    "slug": "metal-vs-shingle-roof-western-nc",
    "title": "Metal vs. Shingle Roofing: What's Best for WNC Mountain Homes?",
    "excerpt": "Comparing the two most popular roofing options for Western North Carolina — cost, durability, and performance at elevation.",
    "category": "Materials",
    "date": "2026-02-10",
    "town": ""
  },
  {
    "slug": "storm-damage-checklist-western-nc",
    "title": "Storm Damage Roof Checklist for Western NC Homeowners",
    "excerpt": "What to look for after a WNC storm — and the steps to take before calling your insurance company.",
    "category": "Storm",
    "date": "2026-02-05",
    "town": ""
  },
  {
    "slug": "best-roofing-materials-highlands-nc",
    "title": "Best Roofing Materials for Highlands, NC Homes",
    "excerpt": "At 4,100+ feet, not every roofing material can handle Highlands weather. Here's what works — and what doesn't.",
    "category": "Materials",
    "date": "2026-01-28",
    "town": "Highlands"
  },
  {
    "slug": "insurance-claim-roof-damage-nc",
    "title": "How to File a Roof Damage Insurance Claim in North Carolina",
    "excerpt": "Step-by-step guide to navigating the insurance claim process for storm-damaged roofs in NC.",
    "category": "Insurance",
    "date": "2026-01-20",
    "town": ""
  },
  {
    "slug": "spring-roof-maintenance-checklist-wnc",
    "title": "Spring Roof Maintenance Checklist for WNC Homeowners",
    "excerpt": "After a mountain winter, your roof needs attention. Here's what to check every spring to prevent costly problems.",
    "category": "Maintenance",
    "date": "2026-01-15",
    "town": "Highlands"
  },
  {
    "slug": "ice-dam-prevention-mountain-homes",
    "title": "How to Prevent Ice Dams on Your Mountain Home Roof",
    "excerpt": "Ice dams cause thousands in damage to WNC homes every winter. Here's how to prevent them.",
    "category": "Maintenance",
    "date": "2026-01-08",
    "town": "Highlands"
  },
  {
    "slug": "when-to-replace-roof-highlands",
    "title": "5 Signs It's Time to Replace Your Roof in Highlands, NC",
    "excerpt": "Not sure if your roof needs repair or full replacement? Here are the warning signs Highlands homeowners should watch for.",
    "category": "Replacement",
    "date": "2025-12-28",
    "town": "Highlands"
  },
  {
    "slug": "roof-inspection-what-to-expect",
    "title": "What to Expect During a Free Roof Inspection in WNC",
    "excerpt": "Never had a professional roof inspection? Here's exactly what our team looks at — and what you'll receive afterward.",
    "category": "Inspections",
    "date": "2025-12-20",
    "town": ""
  },
  {
    "slug": "choosing-roofing-contractor-wnc",
    "title": "How to Choose a Roofing Contractor in Western North Carolina",
    "excerpt": "Not all roofers are equal. Here's what WNC homeowners should look for — and what red flags to avoid.",
    "category": "Tips",
    "date": "2025-12-12",
    "town": ""
  },
  {
    "slug": "emergency-roof-repair-wnc",
    "title": "Emergency Roof Repair in Western NC: What to Do When Disaster Strikes",
    "excerpt": "Fallen tree? Major leak? Here's your step-by-step emergency guide for WNC homeowners.",
    "category": "Storm",
    "date": "2025-12-05",
    "town": ""
  },
  {
    "slug": "roof-financing-options-western-nc",
    "title": "Roof Financing Options for Western NC Homeowners",
    "excerpt": "A new roof is a major investment. Here are the financing options available to make it affordable.",
    "category": "Financing",
    "date": "2025-11-28",
    "town": ""
  },
  {
    "slug": "vacation-rental-roof-maintenance-wnc",
    "title": "Roof Maintenance for WNC Vacation Rental Properties",
    "excerpt": "Your vacation rental's roof is a revenue asset. Here's how to protect it and avoid costly guest disruptions.",
    "category": "Maintenance",
    "date": "2025-11-20",
    "town": "Highlands"
  },
  {
    "slug": "winter-roof-preparation-highlands",
    "title": "Preparing Your Highlands Home Roof for Winter",
    "excerpt": "Mountain winters punish unprepared roofs. Here's how to winterize your Highlands home before the first freeze.",
    "category": "Maintenance",
    "date": "2025-11-12",
    "town": "Highlands"
  },
  {
    "slug": "commercial-roof-maintenance-wnc",
    "title": "Why Every WNC Commercial Property Needs a Roof Maintenance Program",
    "excerpt": "Reactive roofing costs 3x more than preventative maintenance. Here's the business case for commercial roof care.",
    "category": "Commercial",
    "date": "2025-11-05",
    "town": ""
  }
];
